{% set name = "rejson" %}
{% set version = "0.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rejson-{{ version }}.tar.gz
  sha256: 0fd0933412c36f7928d6072efc7d795368342344fc19698341604414cfbc2e6e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - redis-py >=3.0.0
    - six >=1.10

test:
  imports:
    - rejson
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/RedisLabs/rejson-py
  summary: ReJSON Python Client
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
